// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    // Disable automatic URL token detection — we handle the PKCE code exchange
    // manually in AuthContext. This prevents the _getSessionFromURL() crash
    // (TypeError: Invalid value in fetch) that occurs when Supabase tries to
    // parse implicit-flow hash tokens during _initialize().
    detectSessionInUrl: false,
  }
});